fetch_insights:
  description: >
    Search for 3-5 recent and surprising insights about {topic}, using only up-to-date sources (as of 2025).
  expected_output: >
    A bullet list of key facts or discoveries in 2025 related to the topic.

summarize_insights:
  description: >
    Write a short and engaging blog post summary (around 100 words) using the researched facts.
  expected_output: >
    A short blog post that summarizes the insights in an engaging way.
